export interface RawExpenseSeed {
  title: string;
  category: string;
  subCategory?: string;
  period?: string;
  installmentInfo?: string;
  periodStatus?: string;
  dueDateStr?: string;
  amountDue: number;
  amountPaid: number;
  amountRemaining: number;
  status: "PENDING" | "PARTIAL" | "PAID";
  paymentHistory?: { date: string; amount: number; note: string }[];
}

export const INITIAL_EXPENSES_DATA: RawExpenseSeed[] = [
  {
    title: "SGK İcra / Simcu A.Ş.",
    category: "TAX_SGK",
    subCategory: "SGK İcra",
    period: "7.Ay",
    periodStatus: "Cari Dönem",
    dueDateStr: "3 Ağustos 2026 Pazartesi",
    amountDue: 143760,
    amountPaid: 143760,
    amountRemaining: 0,
    status: "PAID",
    paymentHistory: [{ date: "2026-08-03", amount: 143760, note: "Tam Ödeme" }],
  },
  {
    title: "Emre Helvacı / Türkiye Finans KB / SGK",
    category: "CREDIT_CARD",
    subCategory: "Kredi Kartı",
    period: "2t/3t",
    installmentInfo: "2t/3t",
    periodStatus: "KONTROL ET",
    dueDateStr: "4 Ağustos 2026 Salı",
    amountDue: 66435,
    amountPaid: 66435,
    amountRemaining: 0,
    status: "PAID",
    paymentHistory: [{ date: "2026-08-04", amount: 66435, note: "Taksit 2/3 Ödendi" }],
  },
  {
    title: "Ders Saat Ücretli Personel",
    category: "SALARY",
    subCategory: "Maaş",
    period: "6.Ay",
    periodStatus: "Cari Dönem / Güncellendi",
    dueDateStr: "27 Temmuz 2026 Pazartesi",
    amountDue: 23650,
    amountPaid: 23650,
    amountRemaining: 0,
    status: "PAID",
    paymentHistory: [
      { date: "2026-07-27", amount: 11250, note: "1. Parça Ödeme" },
      { date: "2026-07-27", amount: 12400, note: "2. Parça Ödeme" },
    ],
  },
  {
    title: "İlyas Yılmaz",
    category: "RENT",
    subCategory: "Bina Kirası",
    period: "7.Ay",
    periodStatus: "Geçmiş Dönem",
    dueDateStr: "15 Temmuz 2026 Çarşamba",
    amountDue: 76250,
    amountPaid: 76250,
    amountRemaining: 0,
    status: "PAID",
    paymentHistory: [
      { date: "2026-07-15", amount: 40000, note: "1. Parça Kira" },
      { date: "2026-07-15", amount: 36250, note: "2. Parça Kira" },
    ],
  },
  {
    title: "İlyas Yılmaz",
    category: "RENT",
    subCategory: "Bina Kirası",
    period: "8.Ay",
    periodStatus: "Cari Dönem",
    dueDateStr: "15 Ağustos 2026 Cumartesi",
    amountDue: 76250,
    amountPaid: 0,
    amountRemaining: 76250,
    status: "PENDING",
  },
  {
    title: "Özdemirler A.Ş.",
    category: "RENT",
    subCategory: "Mülk Kirası",
    period: "9.Ay",
    periodStatus: "Geçmiş Dönem",
    dueDateStr: "1 Eylül 2026",
    amountDue: 72000,
    amountPaid: 72000,
    amountRemaining: 0,
    status: "PAID",
    paymentHistory: [
      { date: "2026-09-01", amount: 33000, note: "1. Parça" },
      { date: "2026-09-01", amount: 9000, note: "2. Parça" },
      { date: "2026-09-01", amount: 30000, note: "3. Parça" },
    ],
  },
  {
    title: "Özdemirler A.Ş.",
    category: "RENT",
    subCategory: "Mülk Kirası",
    period: "6.Ay",
    periodStatus: "Geçmiş Dönem",
    dueDateStr: "15 Haziran 2026",
    amountDue: 177000,
    amountPaid: 77000,
    amountRemaining: 100000,
    status: "PARTIAL",
    paymentHistory: [{ date: "2026-06-15", amount: 77000, note: "Kısmi Kira Ödemesi" }],
  },
  {
    title: "Özdemirler A.Ş.",
    category: "RENT",
    subCategory: "Mülk Kirası",
    period: "7.Ay",
    periodStatus: "Geçmiş Dönem",
    dueDateStr: "15 Ağustos 2026 Cumartesi",
    amountDue: 177000,
    amountPaid: 0,
    amountRemaining: 177000,
    status: "PENDING",
  },
  {
    title: "Kaski / 351872 / Ziraat KK (SIR YAPI)",
    category: "INVOICE",
    subCategory: "F-Su",
    period: "7.Ay",
    periodStatus: "Cari Dönem / Güncellenecek",
    dueDateStr: "5 Ağustos 2026 Çarşamba",
    amountDue: 5018,
    amountPaid: 5018,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "Kaski / 345406 / Ziraat KK (İLYAS YILMAZ)",
    category: "INVOICE",
    subCategory: "F-Su",
    period: "7.Ay",
    periodStatus: "Cari Dönem / Güncellenecek",
    dueDateStr: "5 Ağustos 2026 Çarşamba",
    amountDue: 1917,
    amountPaid: 1917,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "Vodafone / 7001968355 / Ziraat KK (MT)",
    category: "INVOICE",
    subCategory: "F-Haberleşme",
    period: "5.Ay",
    periodStatus: "Cari Dönem / Güncellenecek",
    dueDateStr: "7 Ağustos 2026 Cuma",
    amountDue: 7198.5,
    amountPaid: 7198.5,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "Mac Denizbank KK",
    category: "CREDIT_CARD",
    subCategory: "Kredi Kartı",
    period: "8.Ay",
    periodStatus: "KONTROL ET / 24'ü Kesim",
    dueDateStr: "3 Ağustos 2026 Pazartesi",
    amountDue: 35515,
    amountPaid: 35515,
    amountRemaining: 0,
    status: "PAID",
    paymentHistory: [
      { date: "2026-08-03", amount: 35350, note: "Ana Ödeme" },
      { date: "2026-08-03", amount: 165, note: "Kalan Bakiye" },
    ],
  },
  {
    title: "SIMCU - PARAF BUSINESS",
    category: "CREDIT_CARD",
    subCategory: "Kredi Kartı",
    period: "8.Ay",
    periodStatus: "KONTROL ET / 2'si Kesim",
    dueDateStr: "7 Ağustos 2026 Cuma",
    amountDue: 43000,
    amountPaid: 43000,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "SIMCU - PARAF ESNAF",
    category: "CREDIT_CARD",
    subCategory: "Kredi Kartı",
    period: "8.Ay",
    periodStatus: "KONTROL ET / 2'si Kesim",
    dueDateStr: "7 Ağustos 2026 Cuma",
    amountDue: 43000,
    amountPaid: 43000,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "ERAY EFE CEVAT KAYIT SİLME İADESİ",
    category: "STUDENT_REFUND",
    subCategory: "Veli İadesi",
    period: "8.Ay",
    periodStatus: "Cari Dönem",
    dueDateStr: "10 Ağustos 2026 Pazartesi",
    amountDue: 22000,
    amountPaid: 22000,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "Alp Tuğrul Karaman - Rıdvan Karaman",
    category: "STUDENT_REFUND",
    subCategory: "Veli İadesi (Taksitli)",
    period: "4t/8t",
    installmentInfo: "4t/8t",
    periodStatus: "Cari Dönem",
    dueDateStr: "10 Ağustos 2026 Pazartesi",
    amountDue: 24500,
    amountPaid: 24500,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "Emre Helvacı / Kuveytturk KK",
    category: "CREDIT_CARD",
    subCategory: "Kredi Kartı",
    period: "2t/3t",
    installmentInfo: "2t/3t",
    periodStatus: "KONTROL ET",
    dueDateStr: "10 Ağustos 2026 Pazartesi",
    amountDue: 26195,
    amountPaid: 26195,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "Kayseri Elektrik A.Ş. (Simcu A.Ş.)",
    category: "INVOICE",
    subCategory: "F-Elektrik",
    period: "6.Ay",
    periodStatus: "KONTROL ET",
    dueDateStr: "10 Ağustos 2026 Pazartesi",
    amountDue: 32294.02,
    amountPaid: 32294.02,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "SIMCU - ZİRAAT KREDİ KARTI",
    category: "CREDIT_CARD",
    subCategory: "Kredi Kartı",
    period: "8.Ay",
    periodStatus: "KONTROL ET",
    dueDateStr: "12 Ağustos 2026 Çarşamba",
    amountDue: 61857.86,
    amountPaid: 61857.86,
    amountRemaining: 0,
    status: "PAID",
    paymentHistory: [
      { date: "2026-08-12", amount: 15000, note: "1. Ödeme" },
      { date: "2026-08-12", amount: 16857.86, note: "2. Ödeme" },
      { date: "2026-08-12", amount: 30000, note: "3. Ödeme" },
    ],
  },
  {
    title: "Ahmet Taymaz / Denizbank 550K Kredi",
    category: "LOAN",
    subCategory: "Banka Kredisi",
    period: "3t/7t",
    installmentInfo: "3t/7t",
    periodStatus: "Cari Dönem",
    dueDateStr: "13 Ağustos 2026 Perşembe",
    amountDue: 38975,
    amountPaid: 38975,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "ALPARSLAN AVAN KAYIT SİLME İADESİ",
    category: "STUDENT_REFUND",
    subCategory: "Veli İadesi (Taksitli)",
    period: "3t/10t",
    installmentInfo: "3t/10t",
    periodStatus: "Cari Dönem",
    dueDateStr: "13 Ağustos 2026 Perşembe",
    amountDue: 23000,
    amountPaid: 23000,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "Millenicom / 0005539476 / Ziraat KK (MAC)",
    category: "INVOICE",
    subCategory: "F-Haberleşme",
    period: "6.Ay",
    periodStatus: "Cari Dönem / Güncellenecek",
    dueDateStr: "14 Ağustos 2026 Cuma",
    amountDue: 1129,
    amountPaid: 1129,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "Öğretmen Maaşları (Toplu Bordro)",
    category: "SALARY",
    subCategory: "Maaş",
    period: "7.Ay",
    periodStatus: "Cari Dönem / Güncellenecek",
    dueDateStr: "15 Ağustos 2026 Cumartesi",
    amountDue: 289950,
    amountPaid: 289950,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "ÇEK ÖDEMESİ - UĞUR GIDA",
    category: "CHEQUE",
    subCategory: "Tedarikçi Çeki",
    period: "8.Ay",
    periodStatus: "Cari Dönem",
    dueDateStr: "15 Ağustos 2026 Cumartesi",
    amountDue: 150000,
    amountPaid: 150000,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "MERYEM HANNE AYAR KAYIT SİLME İADESİ",
    category: "STUDENT_REFUND",
    subCategory: "Veli İadesi (Taksitli)",
    period: "1t/4t",
    installmentInfo: "1t/4t",
    periodStatus: "Cari Dönem",
    dueDateStr: "15 Ağustos 2026 Cumartesi",
    amountDue: 50000,
    amountPaid: 50000,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "Mac İş KK - 4543600343740448",
    category: "CREDIT_CARD",
    subCategory: "Kredi Kartı",
    period: "8.Ay",
    periodStatus: "KONTROL ET / 5'i Kesim",
    dueDateStr: "14 Ağustos 2026 Cuma",
    amountDue: 7200,
    amountPaid: 7200,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "7. Ay Geçici Vergi Ödemesi",
    category: "TAX_SGK",
    subCategory: "Geçici Vergi",
    period: "7.Ay",
    periodStatus: "Cari Dönem",
    dueDateStr: "16 Ağustos 2026 Pazar",
    amountDue: 1085.2,
    amountPaid: 1085.2,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "Kayserigaz / 800005972755 / Ziraat KK (SIR YAPI)",
    category: "INVOICE",
    subCategory: "F-Doğalgaz",
    period: "6.Ay",
    periodStatus: "Cari Dönem",
    dueDateStr: "17 Ağustos 2026 Pazartesi",
    amountDue: 7329,
    amountPaid: 7329,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "GARANTİ BANKASI TOGG TAŞIT KREDİSİ",
    category: "LOAN",
    subCategory: "Taşıt Kredisi",
    period: "8.Ay",
    periodStatus: "CARİ DÖNEM",
    dueDateStr: "17 Ağustos 2026 Pazartesi",
    amountDue: 93640.37,
    amountPaid: 93640.37,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "Türk Telekom / 3525039193 / Ziraat KK (MAC)",
    category: "INVOICE",
    subCategory: "F-Haberleşme",
    period: "6.Ay",
    periodStatus: "Cari Dönem / Güncellenecek",
    dueDateStr: "17 Ağustos 2026 Pazartesi",
    amountDue: 587,
    amountPaid: 587,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "Wis Bina Yönetimi (Isınma & Aidat)",
    category: "INVOICE",
    subCategory: "F-Isınma",
    period: "7.Ay",
    periodStatus: "Cari Dönem / Güncellenecek",
    dueDateStr: "17 Ağustos 2026 Pazartesi",
    amountDue: 7239,
    amountPaid: 7239,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "MEHMED YAHYA ÇAYLAN KAYIT SİLME İADESİ",
    category: "STUDENT_REFUND",
    subCategory: "Veli İadesi",
    period: "8.Ay",
    periodStatus: "Cari Dönem",
    dueDateStr: "17 Ağustos 2026 Pazartesi",
    amountDue: 32000,
    amountPaid: 0,
    amountRemaining: 32000,
    status: "PENDING",
  },
  {
    title: "Adem Tanış Kayıt Silme İadesi",
    category: "STUDENT_REFUND",
    subCategory: "Veli İadesi",
    period: "8.Ay",
    periodStatus: "Cari Dönem",
    dueDateStr: "17 Ağustos 2026 Pazartesi",
    amountDue: 30000,
    amountPaid: 30000,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "Ahmet Taymaz / Akbank 750K Kredi",
    category: "LOAN",
    subCategory: "Banka Kredisi",
    period: "2t/6t",
    installmentInfo: "2t/6t",
    periodStatus: "Cari Dönem",
    dueDateStr: "20 Ağustos 2026 Perşembe",
    amountDue: 48560,
    amountPaid: 0,
    amountRemaining: 48560,
    status: "PENDING",
  },
  {
    title: "SIMCU İş Bankası KK (4146)",
    category: "CREDIT_CARD",
    subCategory: "Kredi Kartı",
    period: "5.Ay",
    periodStatus: "Cari Dönem",
    dueDateStr: "20 Temmuz 2026 Pazartesi",
    amountDue: 8050,
    amountPaid: 8050,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "SIMCU İş Bankası KK (2160)",
    category: "CREDIT_CARD",
    subCategory: "Kredi Kartı",
    period: "5.Ay",
    periodStatus: "Cari Dönem",
    dueDateStr: "20 Temmuz 2026 Pazartesi",
    amountDue: 2280,
    amountPaid: 0,
    amountRemaining: 2280,
    status: "PENDING",
  },
  {
    title: "Duygu Köse / Kuveyttürk KK",
    category: "CREDIT_CARD",
    subCategory: "Kredi Kartı",
    period: "5t/6t",
    installmentInfo: "5t/6t",
    periodStatus: "Cari Dönem",
    dueDateStr: "20 Ağustos 2026 Perşembe",
    amountDue: 15750,
    amountPaid: 0,
    amountRemaining: 15750,
    status: "PENDING",
  },
  {
    title: "Duygu Köse / Halkbank Troy - Vergiler",
    category: "CREDIT_CARD",
    subCategory: "Kredi Kartı",
    period: "8.Ay",
    periodStatus: "Cari Dönem",
    dueDateStr: "20 Ağustos 2026 Perşembe",
    amountDue: 10100,
    amountPaid: 0,
    amountRemaining: 10100,
    status: "PENDING",
  },
  {
    title: "Personel Toplu Maaş Ödemesi",
    category: "SALARY",
    subCategory: "Maaş",
    period: "6.Ay",
    periodStatus: "Cari Dönem / Güncellenecek",
    dueDateStr: "20 Ağustos 2026 Perşembe",
    amountDue: 175890,
    amountPaid: 0,
    amountRemaining: 175890,
    status: "PENDING",
  },
  {
    title: "Ahmet Taymaz / Akbank KK BUSINESS / N11 Sağmacı",
    category: "CREDIT_CARD",
    subCategory: "Kredi Kartı",
    period: "5.Ay",
    periodStatus: "Cari Dönem",
    dueDateStr: "23 Ağustos 2026 Pazar",
    amountDue: 18270,
    amountPaid: 0,
    amountRemaining: 18270,
    status: "PENDING",
  },
  {
    title: "Duygu Köse / Halkbank Master",
    category: "CREDIT_CARD",
    subCategory: "Kredi Kartı",
    period: "5.Ay",
    periodStatus: "Cari Dönem",
    dueDateStr: "31 Ağustos 2026 Pazartesi",
    amountDue: 1380,
    amountPaid: 0,
    amountRemaining: 1380,
    status: "PENDING",
  },
  {
    title: "RUZİYE ÜNSAL TAZMİNAT ÖDEMESİ",
    category: "COMPENSATION",
    subCategory: "Kıdem / İhbar Tazminatı",
    period: "2*4 (Taksitli)",
    installmentInfo: "2t/4t",
    periodStatus: "Cari Dönem",
    dueDateStr: "15 Ağustos 2026 Cumartesi",
    amountDue: 30000,
    amountPaid: 0,
    amountRemaining: 30000,
    status: "PENDING",
  },
  {
    title: "AZRA GÜLCÜ KAYIT SİLME İADESİ",
    category: "STUDENT_REFUND",
    subCategory: "Veli İadesi",
    period: "8.Ay",
    periodStatus: "Cari Dönem",
    dueDateStr: "20 Ağustos 2026 Perşembe",
    amountDue: 27880.52,
    amountPaid: 0,
    amountRemaining: 27880.52,
    status: "PENDING",
  },
  {
    title: "Ahmet Taymaz / Yurt Dışı Harcamaları QNB",
    category: "CREDIT_CARD",
    subCategory: "Kredi Kartı",
    period: "1t/1t",
    installmentInfo: "1t/1t",
    periodStatus: "Cari Dönem",
    dueDateStr: "24 Ağustos 2026 Pazartesi",
    amountDue: 443913.14,
    amountPaid: 0,
    amountRemaining: 443913.14,
    status: "PENDING",
  },
  {
    title: "Emre Helvacı - 5. Ay Maaş Kalanı",
    category: "SALARY",
    subCategory: "Maaş",
    period: "5.Ay",
    periodStatus: "Cari Dönem / Güncellenecek",
    dueDateStr: "27 Temmuz 2026 Pazartesi",
    amountDue: 60000,
    amountPaid: 45000,
    amountRemaining: 15000,
    status: "PARTIAL",
    paymentHistory: [{ date: "2026-07-27", amount: 45000, note: "Kısmi Maaş Ödemesi" }],
  },
  {
    title: "Emre Helvacı - 6. Ay Maaşı",
    category: "SALARY",
    subCategory: "Maaş",
    period: "6.Ay",
    periodStatus: "Cari Dönem / Güncellenecek",
    dueDateStr: "27 Temmuz 2026 Pazartesi",
    amountDue: 70000,
    amountPaid: 0,
    amountRemaining: 70000,
    status: "PENDING",
  },
  {
    title: "Miray Lina Kaya Kayıt Silme İadesi",
    category: "STUDENT_REFUND",
    subCategory: "Veli İadesi (Taksitli)",
    period: "2t/6t",
    installmentInfo: "2t/6t",
    periodStatus: "Cari Dönem",
    dueDateStr: "26 Ağustos 2026 Çarşamba",
    amountDue: 9840,
    amountPaid: 0,
    amountRemaining: 9840,
    status: "PENDING",
  },
  {
    title: "Ahmet Taymaz / Vakıfbank KK",
    category: "CREDIT_CARD",
    subCategory: "Kredi Kartı",
    period: "1t/1t",
    installmentInfo: "1t/1t",
    periodStatus: "Cari Dönem",
    dueDateStr: "27 Temmuz 2026 Pazartesi",
    amountDue: 316325,
    amountPaid: 316325,
    amountRemaining: 0,
    status: "PAID",
  },
  {
    title: "Mac QNB KK",
    category: "CREDIT_CARD",
    subCategory: "Kredi Kartı",
    period: "8.Ay",
    periodStatus: "KONTROL ET / 23'ü Kesim",
    dueDateStr: "29 Ağustos 2026 Cumartesi",
    amountDue: 105000,
    amountPaid: 0,
    amountRemaining: 105000,
    status: "PENDING",
  },
  {
    title: "Ahmet Taymaz / Ev İçin Çekilen Kart (Halkbank)",
    category: "CREDIT_CARD",
    subCategory: "Kredi Kartı",
    period: "1t/6t",
    installmentInfo: "1t/6t",
    periodStatus: "Cari Dönem",
    dueDateStr: "30 Ağustos 2026 Pazar",
    amountDue: 23333.34,
    amountPaid: 0,
    amountRemaining: 23333.34,
    status: "PENDING",
  },
  {
    title: "AROYAL ÇEK ÖDEMESİ (2. Çek)",
    category: "CHEQUE",
    subCategory: "Çek",
    period: "8.Ay",
    periodStatus: "CARİ DÖNEM",
    dueDateStr: "31 Ağustos 2026 Pazartesi",
    amountDue: 125000,
    amountPaid: 0,
    amountRemaining: 125000,
    status: "PENDING",
  },
  {
    title: "SGK YAPILANDIRMA TAKSİTİ",
    category: "TAX_SGK",
    subCategory: "SGK Yapılandırma",
    period: "7.Ay",
    periodStatus: "CARİ DÖNEM",
    dueDateStr: "31 Temmuz 2026 Cuma",
    amountDue: 2250,
    amountPaid: 0,
    amountRemaining: 2250,
    status: "PENDING",
  },
  {
    title: "SGK 7. AY PRİM ÖDEMESİ",
    category: "TAX_SGK",
    subCategory: "SGK Primleri",
    period: "7.Ay",
    periodStatus: "CARİ DÖNEM",
    dueDateStr: "31 Temmuz 2026 Cuma",
    amountDue: 274000,
    amountPaid: 0,
    amountRemaining: 274000,
    status: "PENDING",
  },
  {
    title: "KDV SİMCU ÖDEMESİ",
    category: "TAX_SGK",
    subCategory: "KDV",
    period: "7.Ay",
    periodStatus: "CARİ DÖNEM",
    dueDateStr: "28 Temmuz 2026 Salı",
    amountDue: 28020,
    amountPaid: 0,
    amountRemaining: 28020,
    status: "PENDING",
  },
  {
    title: "MUHTASAR SİMCU ÖDEMESİ",
    category: "TAX_SGK",
    subCategory: "Muhtasar",
    period: "7.Ay",
    periodStatus: "CARİ DÖNEM",
    dueDateStr: "28 Temmuz 2026 Salı",
    amountDue: 28016,
    amountPaid: 0,
    amountRemaining: 28016,
    status: "PENDING",
  },
  {
    title: "KDV MT ÖDEMESİ",
    category: "TAX_SGK",
    subCategory: "KDV",
    period: "7.Ay",
    periodStatus: "CARİ DÖNEM",
    dueDateStr: "28 Temmuz 2026 Salı",
    amountDue: 791,
    amountPaid: 0,
    amountRemaining: 791,
    status: "PENDING",
  },
];
