import { prisma } from "../lib/prisma";

async function main() {
  console.log("9. Ay Gerçek Verileri ve Varlıklar veritabanına aktarılıyor...");

  // Önce mevcut giderleri temizleyip en güncel 9. Ay tablosuyla senkronize edelim
  await prisma.schoolExpense.deleteMany({});
  await prisma.assetTracking.deleteMany({});

  // 1. Örnek Araç & Mülk Kayıtları (Muayene ve Kasko 10 gün kala uyarı testi dahil)
  const today = new Date();
  const dateIn5Days = new Date(today);
  dateIn5Days.setDate(today.getDate() + 5);

  const dateIn8Days = new Date(today);
  dateIn8Days.setDate(today.getDate() + 8);

  const dateIn60Days = new Date(today);
  dateIn60Days.setDate(today.getDate() + 60);

  await prisma.assetTracking.createMany({
    data: [
      {
        title: "38 AB 754 - Ford Transit Okul Servisi",
        assetType: "VEHICLE",
        owner: "Cosmos Koleji Şirket Aracı",
        inspectionDate: dateIn5Days, // 5 gün kaldı! (Uyarı verecek)
        insuranceDate: dateIn60Days,
        kaskoDate: dateIn8Days, // 8 gün kaldı! (Uyarı verecek)
        notes: "TÜVTÜRK muayene randevusu alınacak. Kasko Anadolu Sigorta.",
      },
      {
        title: "34 XYZ 102 - Renault Megane İdari Araç",
        assetType: "VEHICLE",
        owner: "Şirket Binek",
        inspectionDate: dateIn60Days,
        insuranceDate: dateIn60Days,
        kaskoDate: dateIn60Days,
        notes: "Rutin bakım tamamlandı.",
      },
      {
        title: "Kayseri Kampüs Ana Binası (Özdemirler)",
        assetType: "REAL_ESTATE",
        owner: "Özdemirler A.Ş. (Kiralık)",
        housingDate: dateIn8Days, // 8 gün kaldı!
        notes: "Bina DASK ve Yangın Poliçesi yenileme vakti.",
      },
    ],
  });

  // 2. 9. Ay ve Ağustos/Eylül Ödemeleri Listesi (Kullanıcının ilettiği 50+ kalem)
  const expensesData = [
    {
      title: "SGK İcra / Simcu A.Ş.",
      category: "TAX_SGK",
      subCategory: "SGK İcra",
      period: "Cari Dönem",
      monthIndex: 8,
      dueDateStr: "3 Ağustos 2026 Pazartesi",
      amountDue: 143760,
      amountPaid: 143760,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
      paymentHistory: JSON.stringify([{ date: "2026-08-03", amount: 143760, note: "Banka Havale" }]),
    },
    {
      title: "Emre Helvacı / Türkiye Finans KB / SGK",
      category: "CREDIT_CARD",
      subCategory: "Kredi Kartı",
      period: "3t/3t",
      installmentInfo: "3t/3t",
      monthIndex: 8,
      dueDateStr: "4 Ağustos 2026 Salı",
      amountDue: 66435,
      amountPaid: 66435,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CREDIT_CARD",
      cardHolder: "Emre Helvacı",
      cardBank: "Türkiye Finans",
      paymentHistory: JSON.stringify([{ date: "2026-08-04", amount: 66435, note: "KK Ekstre Ödemesi" }]),
    },
    {
      title: "İlyas Yılmaz (Bina Kirası)",
      category: "RENT",
      subCategory: "Bina Kirası",
      period: "8.Ay",
      monthIndex: 8,
      dueDateStr: "15 Eylül 2026 Salı",
      amountDue: 76250,
      amountPaid: 0,
      amountRemaining: 76250,
      status: "PENDING",
      paymentMethod: "CASH",
      periodStatus: "Cari Dönem",
      description: "Yıllık kira anlaşması taksiti - 8. Ay",
    },
    {
      title: "Özdemirler A.Ş. (Mülk Kirası)",
      category: "RENT",
      subCategory: "Mülk Kirası",
      period: "8.Ay",
      monthIndex: 8,
      dueDateStr: "15 Ağustos 2026 Cumartesi",
      amountDue: 100000,
      amountPaid: 100000,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
      periodStatus: "Geçmiş Dönem",
      paymentHistory: JSON.stringify([{ date: "2026-08-15", amount: 100000, note: "Kira Havalesi" }]),
    },
    {
      title: "Özdemirler A.Ş. (Mülk Kirası - 9.Ay 1. Taksit)",
      category: "RENT",
      subCategory: "Mülk Kirası",
      period: "9.Ay",
      monthIndex: 9,
      dueDateStr: "15 Ağustos 2026 Cumartesi",
      amountDue: 177000,
      amountPaid: 0,
      amountRemaining: 177000,
      status: "PENDING",
      paymentMethod: "CASH",
      periodStatus: "Geçmiş Dönem Devir",
      description: "Önceki aydan devreden kira ödemesi",
    },
    {
      title: "Özdemirler A.Ş. (Mülk Kirası - 9.Ay 2. Taksit)",
      category: "RENT",
      subCategory: "Mülk Kirası",
      period: "9.Ay",
      monthIndex: 9,
      dueDateStr: "15 Eylül 2026 Salı",
      amountDue: 177000,
      amountPaid: 0,
      amountRemaining: 177000,
      status: "PENDING",
      paymentMethod: "CASH",
      periodStatus: "Cari Dönem",
      description: "Cari ay kira ödemesi",
    },
    {
      title: "Kaski / 351872 / Ziraat KK (SIR YAPI)",
      category: "INVOICE",
      subCategory: "F-Su",
      period: "8.Ay",
      monthIndex: 8,
      dueDateStr: "5 Eylül 2026 Cumartesi",
      amountDue: 5850,
      amountPaid: 5850,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CREDIT_CARD",
      cardBank: "Ziraat Bankası",
      paymentHistory: JSON.stringify([{ date: "2026-09-05", amount: 5850, note: "Ziraat KK ile ödendi" }]),
    },
    {
      title: "Kaski / 345406 / Ziraat KK (İLYAS YILMAZ)",
      category: "INVOICE",
      subCategory: "F-Su",
      period: "8.Ay",
      monthIndex: 8,
      dueDateStr: "5 Eylül 2026 Cumartesi",
      amountDue: 2294,
      amountPaid: 2294,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CREDIT_CARD",
      cardBank: "Ziraat Bankası",
      paymentHistory: JSON.stringify([{ date: "2026-09-05", amount: 2294, note: "Ziraat KK ile ödendi" }]),
    },
    {
      title: "Vodafone Kurumsal Hatlar (Tek Fatura - 5 Numara)",
      category: "INVOICE",
      subCategory: "F-Haberleşme & Telefon",
      period: "8.Ay",
      monthIndex: 8,
      dueDateStr: "7 Eylül 2026 Pazartesi",
      amountDue: 8269.25,
      amountPaid: 8269.25,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CREDIT_CARD",
      cardHolder: "Ahmet Taymaz",
      cardBank: "Ziraat Bankası",
      isCommitment: true,
      commitmentMonths: 12,
      phoneLines: JSON.stringify([
        { number: "0532 100 00 01", title: "Müdürlük Hattı", commitmentEnd: "2026-11-15" },
        { number: "0532 100 00 02", title: "Muhasebe Hattı", commitmentEnd: "2026-10-20" }, // Yaklaşıyor!
        { number: "0532 100 00 03", title: "Öğrenci İşleri", commitmentEnd: "2027-04-10" },
        { number: "0532 100 00 04", title: "Danışma Hattı", commitmentEnd: "2027-01-15" },
        { number: "0532 100 00 05", title: "Servis Koordinasyon", commitmentEnd: "2026-10-05" }, // Acil!
      ]),
      paymentHistory: JSON.stringify([{ date: "2026-09-07", amount: 8269.25, note: "Otomatik KK Ödemesi" }]),
    },
    {
      title: "Mac Denizbank KK",
      category: "CREDIT_CARD",
      subCategory: "Kredi Kartı",
      monthIndex: 9,
      dueDateStr: "4 Eylül 2026 Cuma",
      amountDue: 12000,
      amountPaid: 12000,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CREDIT_CARD",
      cardBank: "Denizbank",
      description: "Hesap kesim: 24'ü",
    },
    {
      title: "SIMCU - PARAF BUSINESS",
      category: "CREDIT_CARD",
      subCategory: "Kredi Kartı",
      monthIndex: 9,
      dueDateStr: "7 Eylül 2026 Pazartesi",
      amountDue: 57900,
      amountPaid: 57900,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CREDIT_CARD",
      cardBank: "Halkbank",
      description: "Hesap kesim: 2'si",
    },
    {
      title: "SIMCU - PARAF ESNAF",
      category: "CREDIT_CARD",
      subCategory: "Kredi Kartı",
      monthIndex: 9,
      dueDateStr: "7 Eylül 2026 Pazartesi",
      amountDue: 47900,
      amountPaid: 47900,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CREDIT_CARD",
      cardBank: "Halkbank",
      description: "Hesap kesim: 2'si",
    },
    {
      title: "ERAY EFE CEVAT KAYIT SİLME İADESİ",
      category: "STUDENT_REFUND",
      subCategory: "Kayıt Silme",
      monthIndex: 9,
      dueDateStr: "10 Eylül 2026 Perşembe",
      amountDue: 22000,
      amountPaid: 22000,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
    },
    {
      title: "Alp Tuğrul Karaman - Rıdvan Karaman",
      category: "STUDENT_REFUND",
      subCategory: "Kayıt Silme",
      period: "5t/8t",
      installmentInfo: "5t/8t",
      monthIndex: 9,
      dueDateStr: "10 Eylül 2026 Perşembe",
      amountDue: 24500,
      amountPaid: 24500,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
    },
    {
      title: "Emre Helvacı / Kuveytturk KK",
      category: "CREDIT_CARD",
      subCategory: "Kredi Kartı",
      period: "3t/3t",
      installmentInfo: "3t/3t",
      monthIndex: 9,
      dueDateStr: "10 Eylül 2026 Perşembe",
      amountDue: 26195,
      amountPaid: 26195,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CREDIT_CARD",
      cardHolder: "Emre Helvacı",
      cardBank: "Kuveyt Türk",
    },
    {
      title: "Kayseri Elektrik A.Ş. (Simcu A.Ş.)",
      category: "INVOICE",
      subCategory: "F-Elektrik",
      period: "8.Ay",
      monthIndex: 8,
      dueDateStr: "9 Eylül 2026 Çarşamba",
      amountDue: 44635.99,
      amountPaid: 44635.99,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
    },
    {
      title: "YAĞIZ EFE TUTUM AYMİRA TUTUM KAYIT SİLME",
      category: "STUDENT_REFUND",
      subCategory: "Kayıt Silme",
      period: "2t/3t",
      installmentInfo: "2t/3t",
      monthIndex: 8,
      dueDateStr: "10 Ağustos 2026 Pazartesi",
      amountDue: 32695,
      amountPaid: 32695,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
    },
    {
      title: "EREN HAKKOMAZ KAYIT SİLME İADESİ",
      category: "STUDENT_REFUND",
      subCategory: "Kayıt Silme",
      period: "1t/6t",
      installmentInfo: "1t/6t",
      monthIndex: 8,
      dueDateStr: "10 Ağustos 2026 Pazartesi",
      amountDue: 6250,
      amountPaid: 6250,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
    },
    {
      title: "SIMCU - ZİRAAT KART",
      category: "CREDIT_CARD",
      subCategory: "Kredi Kartı",
      monthIndex: 9,
      dueDateStr: "14 Eylül 2026 Pazartesi",
      amountDue: 54000,
      amountPaid: 54000,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CREDIT_CARD",
      cardBank: "Ziraat Bankası",
    },
    {
      title: "Ahmet Taymaz / Denizbank 550K Kredi",
      category: "LOAN",
      subCategory: "Banka Kredisi",
      period: "4t/7t",
      installmentInfo: "4t/7t",
      monthIndex: 9,
      dueDateStr: "13 Eylül 2026 Pazar",
      amountDue: 38975,
      amountPaid: 38975,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
      cardHolder: "Ahmet Taymaz",
    },
    {
      title: "ALPARSLAN AVAN KAYIT SİLME İADESİ",
      category: "STUDENT_REFUND",
      subCategory: "Kayıt Silme",
      period: "4t/10t",
      installmentInfo: "4t/10t",
      monthIndex: 8,
      dueDateStr: "13 Ağustos 2026 Perşembe",
      amountDue: 23000,
      amountPaid: 23000,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
    },
    {
      title: "Millenicom İnternet / Ziraat KK (MAC)",
      category: "INVOICE",
      subCategory: "F-Haberleşme & İnternet",
      period: "8.Ay",
      monthIndex: 8,
      dueDateStr: "14 Ağustos 2026 Cuma",
      amountDue: 1129,
      amountPaid: 1129,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CREDIT_CARD",
      cardBank: "Ziraat Bankası",
      isCommitment: true,
      commitmentMonths: 12,
    },
    {
      title: "Öğretmen Maaş Ödemeleri (Toplam)",
      category: "SALARY",
      subCategory: "Maaş",
      period: "8.Ay",
      monthIndex: 8,
      dueDateStr: "15 Ağustos 2026 Cumartesi",
      amountDue: 283909.7,
      amountPaid: 283909.7,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
    },
    {
      title: "AYSİMA ÇAĞIR OKUL TAKSİTİ",
      category: "OTHER",
      subCategory: "Okul Taksiti",
      period: "1/9TAKSİT",
      installmentInfo: "1t/9t",
      monthIndex: 9,
      dueDateStr: "15 Eylül 2026 Salı",
      amountDue: 20000,
      amountPaid: 20000,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
    },
    {
      title: "MERYEM HANNE AYAR KAYIT SİLME İADESİ",
      category: "STUDENT_REFUND",
      subCategory: "Kayıt Silme",
      period: "2t/4t",
      installmentInfo: "2t/4t",
      monthIndex: 8,
      dueDateStr: "15 Ağustos 2026 Cumartesi",
      amountDue: 50000,
      amountPaid: 50000,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
    },
    {
      title: "GARANTİ BANKASI TOGG KREDİSİ",
      category: "LOAN",
      subCategory: "Araç Kredisi",
      period: "8.Ay",
      monthIndex: 8,
      dueDateStr: "17 Ağustos 2026 Pazartesi",
      amountDue: 93640.37,
      amountPaid: 93640.37,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
    },
    {
      title: "Ahmet Taymaz / Akbank 750K Kredi",
      category: "LOAN",
      subCategory: "Banka Kredisi",
      period: "3t/6t",
      installmentInfo: "3t/6t",
      monthIndex: 8,
      dueDateStr: "20 Ağustos 2026 Perşembe",
      amountDue: 48560,
      amountPaid: 48560,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
      cardHolder: "Ahmet Taymaz",
    },
    {
      title: "Duygu Köse / Kuveytturk KK",
      category: "CREDIT_CARD",
      subCategory: "Kredi Kartı",
      period: "6t/6t",
      installmentInfo: "6t/6t",
      monthIndex: 8,
      dueDateStr: "20 Ağustos 2026 Perşembe",
      amountDue: 15750,
      amountPaid: 15750,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CREDIT_CARD",
      cardHolder: "Duygu Köse",
      cardBank: "Kuveyt Türk",
    },
    {
      title: "Duygu Köse / Halkbank Troy - Vergiler",
      category: "CREDIT_CARD",
      subCategory: "Kredi Kartı",
      monthIndex: 8,
      dueDateStr: "20 Ağustos 2026 Perşembe",
      amountDue: 10100,
      amountPaid: 10100,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CREDIT_CARD",
      cardHolder: "Duygu Köse",
      cardBank: "Halkbank",
    },
    {
      title: "Personel Maaş Ödemeleri (Toplam)",
      category: "SALARY",
      subCategory: "Maaş",
      period: "8.Ay",
      monthIndex: 8,
      dueDateStr: "20 Ağustos 2026 Perşembe",
      amountDue: 128086,
      amountPaid: 128086,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
    },
    {
      title: "Ahmet Taymaz / Akbank KK BUSINESS (N11 Sağmacı)",
      category: "CREDIT_CARD",
      subCategory: "Kredi Kartı",
      period: "8.Ay",
      monthIndex: 8,
      dueDateStr: "23 Ağustos 2026 Pazar",
      amountDue: 18270,
      amountPaid: 18270,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CREDIT_CARD",
      cardHolder: "Ahmet Taymaz",
      cardBank: "Akbank",
    },
    {
      title: "Duygu Köse / Halkbank Master KK",
      category: "CREDIT_CARD",
      subCategory: "Kredi Kartı",
      period: "8.Ay",
      monthIndex: 8,
      dueDateStr: "31 Ağustos 2026 Pazartesi",
      amountDue: 1380,
      amountPaid: 1380,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CREDIT_CARD",
      cardHolder: "Duygu Köse",
      cardBank: "Halkbank",
    },
    {
      title: "RUZİYE ÜNSAL TAZMİNAT ÖDEMESİ",
      category: "COMPENSATION",
      subCategory: "Tazminat",
      period: "3*4",
      monthIndex: 8,
      dueDateStr: "15 Ağustos 2026 Cumartesi",
      amountDue: 30000,
      amountPaid: 30000,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
    },
    {
      title: "İSMAİL ATA KOÇER İADE",
      category: "STUDENT_REFUND",
      subCategory: "Kayıt Silme",
      monthIndex: 8,
      dueDateStr: "20 Ağustos 2026 Perşembe",
      amountDue: 50000,
      amountPaid: 50000,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
    },
    {
      title: "Emre Helvacı - Maaş Ödemesi",
      category: "SALARY",
      subCategory: "Maaş",
      period: "8.Ay",
      monthIndex: 9,
      dueDateStr: "25 Eylül 2026 Cuma",
      amountDue: 65000,
      amountPaid: 0,
      amountRemaining: 65000,
      status: "PENDING",
      paymentMethod: "CASH",
      periodStatus: "Cari Dönem / Bekliyor",
    },
    {
      title: "Miray Lina Kaya - Kayıt Silme İadesi",
      category: "STUDENT_REFUND",
      subCategory: "Kayıt Silme",
      period: "4t/6t",
      installmentInfo: "4t/6t",
      monthIndex: 9,
      dueDateStr: "26 Eylül 2026 Cumartesi",
      amountDue: 9840,
      amountPaid: 0,
      amountRemaining: 9840,
      status: "PENDING",
      paymentMethod: "CASH",
      periodStatus: "Cari Dönem / Bekliyor",
    },
    // AHMET TAYMAZ / VAKIFBANK KK - 2 KISMI ÖDEMELİ GERÇEK KAYIT!
    {
      title: "Ahmet Taymaz / Vakıfbank KK",
      category: "CREDIT_CARD",
      subCategory: "Kredi Kartı",
      period: "1t/1t",
      monthIndex: 9,
      dueDateStr: "25 Eylül 2026 Cuma",
      amountDue: 551896,
      amountPaid: 420000, // 150.000 + 270.000
      amountRemaining: 131896,
      status: "PARTIAL",
      paymentMethod: "CREDIT_CARD",
      cardHolder: "Ahmet Taymaz",
      cardBank: "Vakıfbank",
      description: "Hesap ekstresi parçalı ödemesi (2 taksit ödendi, 131.896 TL kaldı)",
      paymentHistory: JSON.stringify([
        { date: "2026-09-10", amount: 150000, note: "1. Kısmi Ödeme (Vakıfbank Havale)" },
        { date: "2026-09-20", amount: 270000, note: "2. Kısmi Ödeme (Vakıfbank Havale)" },
      ]),
    },
    {
      title: "Mac QNB Kredi Kartı",
      category: "CREDIT_CARD",
      subCategory: "Kredi Kartı",
      monthIndex: 9,
      dueDateStr: "29 Eylül 2026 Salı",
      amountDue: 105000,
      amountPaid: 0,
      amountRemaining: 105000,
      status: "PENDING",
      paymentMethod: "CREDIT_CARD",
      cardBank: "QNB Finansbank",
      description: "Hesap kesim: 23'ü",
    },
    {
      title: "Ahmet Taymaz / Halkbankası KK",
      category: "CREDIT_CARD",
      subCategory: "Kredi Kartı",
      monthIndex: 9,
      dueDateStr: "30 Eylül 2026 Çarşamba",
      amountDue: 3535,
      amountPaid: 0,
      amountRemaining: 3535,
      status: "PENDING",
      paymentMethod: "CREDIT_CARD",
      cardHolder: "Ahmet Taymaz",
      cardBank: "Halkbank",
    },
    {
      title: "Ahmet Taymaz / Akbank KK",
      category: "CREDIT_CARD",
      subCategory: "Kredi Kartı",
      monthIndex: 9,
      dueDateStr: "30 Eylül 2026 Çarşamba",
      amountDue: 3055,
      amountPaid: 0,
      amountRemaining: 3055,
      status: "PENDING",
      paymentMethod: "CREDIT_CARD",
      cardHolder: "Ahmet Taymaz",
      cardBank: "Akbank",
    },
    {
      title: "Aydın5 (MAC Harcaması)",
      category: "OTHER",
      subCategory: "Gider",
      monthIndex: 9,
      dueDateStr: "30 Eylül 2026 Çarşamba",
      amountDue: 3865,
      amountPaid: 0,
      amountRemaining: 3865,
      status: "PENDING",
      paymentMethod: "CASH",
    },
    {
      title: "SGK Yapılandırma 7044 (Vakıfbank / Halkbank)",
      category: "TAX_SGK",
      subCategory: "Yapılandırma",
      monthIndex: 8,
      dueDateStr: "31 Temmuz 2026 Cuma",
      amountDue: 2250,
      amountPaid: 2250,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
    },
    {
      title: "SGK Yapılandırma (AT Kart - Her Ayın 5'i)",
      category: "TAX_SGK",
      subCategory: "Yapılandırma",
      monthIndex: 8,
      dueDateStr: "31 Temmuz 2026 Cuma",
      amountDue: 149958.85,
      amountPaid: 149958.85,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CREDIT_CARD",
      cardHolder: "Ahmet Taymaz",
    },
    {
      title: "SGK 8. Ay Prim Ödemesi",
      category: "TAX_SGK",
      subCategory: "SGK Prim",
      monthIndex: 8,
      dueDateStr: "31 Temmuz 2026 Cuma",
      amountDue: 198100.7,
      amountPaid: 198100.7,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
    },
    {
      title: "SİMCU Stopaj & Muhtasar",
      category: "TAX_SGK",
      subCategory: "Vergi",
      monthIndex: 9,
      dueDateStr: "28 Eylül 2026 Pazartesi",
      amountDue: 9065.13,
      amountPaid: 9065.13,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
    },
    {
      title: "KDV Ödemesi (MT)",
      category: "TAX_SGK",
      subCategory: "Vergi",
      monthIndex: 9,
      dueDateStr: "28 Eylül 2026 Pazartesi",
      amountDue: 791,
      amountPaid: 791,
      amountRemaining: 0,
      status: "PAID",
      paymentMethod: "CASH",
    },
    // VERİLEN ÇEK ÖRNEĞİ (Kullanıcı listesindeki ÇEK ÖDEMESİ - UĞUR GIDA)
    {
      title: "Çek Ödemesi - Uğur Gıda San. Tic.",
      category: "CHEQUE",
      subCategory: "Tedarikçi Çeki",
      monthIndex: 10,
      dueDateStr: "15 Ekim 2026 Perşembe",
      amountDue: 45000,
      amountPaid: 0,
      amountRemaining: 45000,
      status: "PENDING",
      paymentMethod: "CHEQUE",
      chequeNo: "TR-884219",
      chequeBank: "Halkbank Kayseri Şubesi",
      description: "Yemekhane kuru gıda alımı 60 gün vadeli çek",
    },
  ];

  for (const exp of expensesData) {
    await prisma.schoolExpense.create({
      data: exp as any,
    });
  }

  console.log(`Tamamlandı: ${expensesData.length} adet 9. ay ödeme kaydı ve varlıklar sisteme eklendi.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
